### PR TITLE
chore: ignore lockfile

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by ckiee** [comment]
you should also add yarn.lock

**Comment by DanielRuf** [comment]
Hi @RONTheCookie, this project uses npm and has the lockfile of npm committed. This PR is meant to prevent this in the future.

**Comment by DanielRuf** [comment]
Hi @RONTheCookie, this project uses npm and has the lockfile of npm committed. This PR is meant to remove this file and prevent this in the future.

**Comment by ckiee** [comment]
Yeah but it would still be convenient for people that use yarn anyway.

**Comment by DanielRuf** [comment]
Bump.

**Pull request closed without merging**
